estimation_tool/urls.py
from django.conf.urls import patterns, include, url
from BET.views import hello
from BET.views import current_datetime
from django.contrib import admin
#from haystack.views import SearchView
from BET.forms import *
# Without threading...

# urlpatterns = patterns('haystack.views',
#     url(r'^search/$', SearchView(
#         template='search/search.html',
#         form_class=PinsRangeSearchForm,
#     ), name='search'),
# )

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'estimation_tool.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^time/$', current_datetime),
    url(r'^hello/$', hello),
    #url(r'^search/$', include('haystack.urls')),
    url(r'^showdetail/(?P<part_number>[\d-]+)/$', 'BET.views.show_detail', name='showdetail'),
    url(r'^showdetail/(?P<part_number>[\d-]+)/showsimilar/$', 'BET.views.show_similar', name='showthesimilar'),
    url(r'^showdetail/(?P<part_num>[\d-]+)/formula/$', 'BET.views.show_est_formula', name='showformula'),
    url(r'^accounts/login/$',  'BET.views.login', name='login'),
    url(r'^index/$',  'BET.views.index', name='index'),
    url(r'^search/$',  'BET.views.index2', name='search'),
    url(r'^advancedsearch/$',  'BET.views.AdvancedSearch', name='advancedsearch'),
)

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class BetBrdmapdat(models.Model):
    part_number = models.CharField(db_column='Part_number', primary_key=True, max_length=100) # Field name made lowercase.
    dat_file_location = models.CharField(db_column='Dat_file_location', max_length=500) # Field name made lowercase.
    brd_file_location = models.CharField(db_column='Brd_file_location', max_length=500) # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'BET_brdmapdat'

class BetCombine(models.Model):
    part_number = models.CharField(db_column='Part_number', primary_key=True, max_length=80) # Field name made lowercase.
    project_name = models.CharField(db_column='Project Name', max_length=300, blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    part_name = models.CharField(db_column='Part Name', max_length=300) # Field name made lowercase. Field renamed to remove unsuitable characters.
    category = models.CharField(db_column='Category', max_length=45, blank=True) # Field name made lowercase.
    total_days = models.FloatField(db_column='Total Days', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    estimated_total_days = models.FloatField(db_column='Estimated Total Days', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    adjusted_days = models.FloatField(db_column='Adjusted Days', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    board_width = models.FloatField(db_column='Board Width', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    board_height = models.FloatField(db_column='Board Height', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    metal_to_metal_thickness = models.FloatField(db_column='Metal to Metal Thickness', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    sequential_lam = models.CharField(db_column='Sequential Lam', max_length=3, blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    via_type_buried = models.CharField(db_column='Via Type:Buried', max_length=3, blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    via_type_blind = models.CharField(db_column='Via Type:Blind', max_length=3, blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    total_layers = models.IntegerField(db_column='Total Layers', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    plane_layers = models.IntegerField(db_column='Plane Layers', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    pins = models.IntegerField(db_column='Pins', blank=True, null=True) # Field name made lowercase.
    connections = models.IntegerField(db_column='Connections', blank=True, null=True) # Field name made lowercase.
    components = models.IntegerField(db_column='Components', blank=True, null=True) # Field name made lowercase.
    total_nets = models.IntegerField(db_column='Total Nets', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    bga_lgas = models.IntegerField(db_column='BGA/LGAs', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    dimms = models.IntegerField(db_column='DIMMs', blank=True, null=True) # Field name made lowercase.
    pin_density = models.FloatField(blank=True, null=True)
    component_density = models.FloatField(blank=True, null=True)
    buses = models.IntegerField(db_column='Buses', blank=True, null=True) # Field name made lowercase.
    constraintsets = models.IntegerField(db_column='Constraintsets', blank=True, null=True) # Field name made lowercase.
    diffpairs = models.IntegerField(db_column='Diffpairs', blank=True, null=True) # Field name made lowercase.
    matchgroups = models.IntegerField(db_column='Matchgroups', blank=True, null=True) # Field name made lowercase.
    netclasses = models.IntegerField(db_column='Netclasses', blank=True, null=True) # Field name made lowercase.
    net_with_constraints = models.IntegerField(db_column='Net with Constraints', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    pinpairs = models.IntegerField(db_column='Pinpairs', blank=True, null=True) # Field name made lowercase.
    xnets = models.IntegerField(db_column='Xnets', blank=True, null=True) # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'BET_combine'

class BetCombine2(models.Model):
    part_number = models.CharField(db_column='Part_number', primary_key=True, max_length=80) # Field name made lowercase.
    part_name = models.CharField(db_column='Part Name', max_length=300) # Field name made lowercase. Field renamed to remove unsuitable characters.
    project_name = models.CharField(db_column='Project Name', max_length=300) # Field name made lowercase. Field renamed to remove unsuitable characters.
    category = models.CharField(db_column='Category', max_length=45) # Field name made lowercase.
    total_days = models.FloatField(db_column='Total Days', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    estimated_total_days = models.FloatField(db_column='Estimated Total Days', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    adjusted_days = models.FloatField(db_column='Adjusted Days', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    board_width = models.FloatField(db_column='Board Width', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    board_height = models.FloatField(db_column='Board Height', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    metal_to_metal_thickness = models.FloatField(db_column='Metal to Metal Thickness', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    sequential_lam = models.CharField(db_column='Sequential Lam', max_length=3, blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    via_type_buried = models.CharField(db_column='Via Type:Buried', max_length=3, blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    via_type_blind = models.CharField(db_column='Via Type:Blind', max_length=3, blank=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    total_layers = models.IntegerField(db_column='Total Layers', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    plane_layers = models.IntegerField(db_column='Plane Layers', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    pins = models.IntegerField(db_column='Pins', blank=True, null=True) # Field name made lowercase.
    connections = models.IntegerField(db_column='Connections', blank=True, null=True) # Field name made lowercase.
    components = models.IntegerField(db_column='Components', blank=True, null=True) # Field name made lowercase.
    total_nets = models.IntegerField(db_column='Total Nets', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    bga_lgas = models.IntegerField(db_column='BGA/LGAs', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    dimms = models.IntegerField(db_column='DIMMs', blank=True, null=True) # Field name made lowercase.
    pin_density = models.FloatField(blank=True, null=True)
    component_density = models.FloatField(blank=True, null=True)
    buses = models.IntegerField(db_column='Buses', blank=True, null=True) # Field name made lowercase.
    constraintsets = models.IntegerField(db_column='Constraintsets', blank=True, null=True) # Field name made lowercase.
    diffpairs = models.IntegerField(db_column='Diffpairs', blank=True, null=True) # Field name made lowercase.
    matchgroups = models.IntegerField(db_column='Matchgroups', blank=True, null=True) # Field name made lowercase.
    netclasses = models.IntegerField(db_column='Netclasses', blank=True, null=True) # Field name made lowercase.
    net_with_constraints = models.IntegerField(db_column='Net with Constraints', blank=True, null=True) # Field name made lowercase. Field renamed to remove unsuitable characters.
    pinpairs = models.IntegerField(db_column='Pinpairs', blank=True, null=True) # Field name made lowercase.
    xnets = models.IntegerField(db_column='Xnets', blank=True, null=True) # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'BET_combine2'

class BetPhysicalboard(models.Model):
    part_number = models.CharField(db_column='Part_number', primary_key=True, max_length=80) # Field name made lowercase.
    part_name = models.CharField(db_column='Part Name', max_length=300) # Field name made lowercase. Field renamed to remove unsuitable characters.

BET/forms.py
__author__ = 'yaxxu'
from django import forms
# from haystack.forms import SearchForm
# from haystack.query import *
from models import *
from django.contrib.auth.models import User
from bootstrap_toolkit.widgets import BootstrapDateInput, BootstrapTextInput, BootstrapUneditableInput
from django.core.exceptions import ObjectDoesNotExist
import subprocess
import MySQLdb
from extract_statistics import *
from django.db import connections
#
# class SearchForm(forms.Form):
#     def no_query_found(self):
#         return EmptySearchQuerySet()

class AdvancedSearchForm(forms.Form):
    pin_lower_bound = forms.IntegerField(required=False, label='Pins Lower Bound')
    pin_upper_bound = forms.IntegerField(required=False, label='Pins Upper Bound')
    component_lower_bound = forms.IntegerField(required=False, label='Components Lower Bound')
    component_upper_bound = forms.IntegerField(required=False, label='Components Upper Bound')
    pin_density_lower = forms.IntegerField(required=False, label='Pin Density Lower Bound')
    pin_density_upper = forms.IntegerField(required=False, label='Pin Density Upper Bound')
    board_size_lower = forms.IntegerField(required=False, label='Board Size Lower Bound')
    board_size_upper = forms.IntegerField(required=False, label='Board Size Upper Bound')
    def search(self):
        # # First, store the SearchQuerySet received from other processing.
        sqs = Combine.objects.all()

        if not self.is_valid():
            return sqs

        sqs = sqs.order_by('pins')

        if self.cleaned_data['pin_lower_bound']:
            sqs = sqs.filter(pins__gte=self.cleaned_data['pin_lower_bound'])

        if self.cleaned_data['pin_upper_bound']:
            sqs = sqs.filter(pins__lte=self.cleaned_data['pin_upper_bound'])

        if self.cleaned_data['component_lower_bound']:
            sqs = sqs.filter(components__gte=self.cleaned_data['component_lower_bound'])

        if self.cleaned_data['component_upper_bound']:
            sqs = sqs.filter(components__lte=self.cleaned_data['component_upper_bound'])

        if self.cleaned_data['pin_density_lower']:
            sqs = sqs.filter(pin_density__gte=self.cleaned_data['pin_density_lower'])

        if self.cleaned_data['pin_density_upper']:
            sqs = sqs.filter(pin_density__lte=self.cleaned_data['pin_density_upper'])

        if self.cleaned_data['board_size_lower']:
            sqs = sqs.filter(board_width__gte=self.cleaned_data['board_size_lower'])

        if self.cleaned_data['board_size_upper']:
            sqs = sqs.filter(board_width__lte=self.cleaned_data['board_size_upper'])

        return sqs


# class SearchByPartNumber(SearchForm):
#     def search(self):
#         # # First, store the SearchQuerySet received from other processing.
#         sqs = super(SearchByPartNumber, self).search()
#
#         if not self.is_valid():
#             return sqs
#
#         return sqs

# class FacetedSearchView(SearchView):
#     def extra_context(self):
#         extra = super(FacetedSearchView, self).extra_context()
#
#         if self.results == []:
#             extra['facets'] = self.form.search().facet_counts()
#         else:
#             extra['facets'] = self.results.facet_counts()
#
#         return extra

class RangeForm(forms.Form):
    pin_diff = forms.IntegerField(required=False)
    component_diff = forms.IntegerField(required=False)
    pin_density_diff = forms.FloatField(required=False)
    adjusteddays = forms.FloatField(required=False)
    actualdays = forms.FloatField(required=False)

class NewTaskForm(forms.Form):
    category = forms.CharField(required=False, label=u"Category")
    part_number2 = forms.CharField(required=True, label=u"Part Number",widget=forms.TextInput(attrs={'size': '20'}))
    dat_file_location = forms.CharField(required=True, label=u"Dat Files",widget=forms.TextInput(attrs={'size': '150'}))
    def get_statistics(self):
        partnumber = self.cleaned_data['part_number2']
        directory =self.cleaned_data['dat_file_location']
        print directory
        try:
            #connect to JTS get the information
            query = PartInfo.objects.using('JTS').get(part_number=partnumber)
            # create the board file and the reports. Skill programming script called
            # subprocess.call(['O:\usr2\engcheck\Estimation_tool\scripts\bet.bat', directory, str(query.board_height), str(query.board_width)], shell=True)
        except:
            err="Cannot find records for %s in JTS or the directory given is invalid" %(partnumber)
            return err
        # extract information from reports.
        try:
            check = Combine.objects.get(part_number=partnumber)
            err = 'Warning! overwriting existing data in databases! Part number %s already exists in our database' %(partnumber)
        except:
            err = 'Success!'
        finally:
            newtask = getstatistics(directory)
            newtask = getbigcomponents(directory,newtask)
            newtask = getconstraints(directory,newtask)
            newtask.part_name = query.part_name
            newtask.project_name = query.project_name
            newtask.board_width = query.board_width
            newtask.board_height = query.board_height
            print newtask.pins, newtask.constraintsets
            # except:
            #     err='Part Number not Found in JTS or No Such Directory'
            #     return err
            #add this new board to our data base
            #newtask.save(using='BET_NEW')
            return (err,newtask)


class SingleSearchForm(forms.Form):
    part_number = forms.CharField(required=True, label=u"Part Number",widget=forms.TextInput(attrs={'size': '30'}))

class LoginForm(forms.Form):
    username = forms.CharField(
        required=True,
        label=u"Username",
        error_messages={'required': 'Please input username'},
        widget=forms.TextInput(
            attrs={
                'placeholder': u"Username",
            }
        ),
    )
    password = forms.CharField(
        required=True,
        label=u"Password",
        error_messages={'required': u'Please input password'},
        widget=forms.PasswordInput(
            attrs={
                'placeholder':u"password",
            }
        ),
    )
    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError(u"Username and password required")
        else:
            cleaned_data = super(LoginForm, self).clean()

templates/search/advancedsearch.html
{% extends 'base.html' %}
{% block advancedsearch %}
     <div class="container">
        <div class="well">
            <h2>Search For Boards</h2>
            <form class="form-horizontal" method="post" action=".">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">Pins</div>
                <div class="col-md-4">
                <label for="id_pin_lower_bound">from:</label>
                    <input id="id_pin_lower_bound" type="text" name="pin_lower_bound" maxlength="100" /></div>
                <div class="col-md-4">
                <label for="id_pin_upper_bound">to:</label>
                    <input id="id_pin_upper_bound" type="text" name="pin_upper_bound" maxlength="100" /></div>
            </div>

            <div class="row">
                <div class="col-md-4">Components</div>
                <div class="col-md-4">
                <label for="id_component_lower_bound">from:</label>
                    <input id="id_component_lower_bound" type="text" name="component_lower_bound" maxlength="100" /></div>
                <div class="col-md-4">
                <label for="id_component_upper_bound">to:</label>
                    <input id="id_component_upper_bound" type="text" name="component_upper_bound" maxlength="100" /></div>
            </div>

            <div class="row">
                <div class="col-md-4">Pin Density</div>
                <div class="col-md-4">
                <label for="id_pin_density_lower">from:</label>
                    <input id="id_pin_density_lower" type="text" name="pin_density_lower" maxlength="100" /></div>
                <div class="col-md-4">
                <label for="id_pin_density_upper">to:</label>
                    <input id="id_pin_density_upper" type="text" name="pin_density_upper" maxlength="100" /></div>
            </div>

            <div class="row">
                <div class="col-md-4">Boardsize</div>
                <div class="col-md-4">
                <label for="id_board_size_lower">from:</label>
                    <input id="id_board_size_lower" type="text" name="board_size_lower" maxlength="100" /></div>
                <div class="col-md-4">
                <label for="id_board_size_upper">to:</label>
                    <input id="id_board_size_upper" type="text" name="board_size_upper" maxlength="100" /></div>
            </div>

            <p class="form-actions">
                <input type="submit" value="Search" class="btn btn-primary">
            </p>
            </form>
        </div>
     </div>
        {%if queryset%}
                <h3>Results</h3>
                <table class="table table-striped">
                <tr>
                    <tr>
                      <th>Part Number</th>
                      <th>Part Name</th>
                      <th>Estimated Time</th>
                      <th>Actual Time</th>
                      <th>Pins</th>
                      <th>Components</th>
                      <th>Pin_density</th>
                      <th>Width</th>
                      <th>Height</th>
                      <th>Total Layers</th>
                      <th>Buses</th>
                      <th>Constraint Sets</th>
                      <th>Diff Pairs</th>
                      <th>Match Groups</th>
                      <th>Net Classes</th>
                      <th>Net With Constraints</th>
                      <th>Pin Pairs</th>
                      <th>Xnets</th>
                    </tr>
                </tr>
                {% for result in queryset %}
                <tr>
                      <td><a href="{% url 'showdetail' result.part_number%}">{{ result.part_number }}</a> </td>
                      <td>{{ result.part_name }}</td>
                      <td>{{ result.estimated_total_days }}</td>
                      <td>{{ result.total_days }}</td>
                      <td>{{ result.pins }}</td>
                      <td>{{ result.components}}</td>
                      <td>{{ result.pin_density}}</td>
                      <td>{{ result.board_width}}</td>
                      <td>{{ result.board_height}}</td>
                      <td>{{ result.total_layers }}</td>
                      <td>{{ result.buses }}</td>
                      <td>{{ result.constraintsets }}</td>
                      <td>{{ result.diffpairs }}</td>
                      <td>{{ result.matchgroups}}</td>
                      <td>{{ result.netclasses}}</td>
                      <td>{{ result.net_with_constraints}}</td>
                      <td>{{ result.pinpairs}}</td>
                      <td>{{ result.xnets}}</td>
                </tr>

                {% empty %}
                    <p>No results found.</p>
                {% endfor %}
                </table>
            {%endif%}


{% endblock %}

templates/search/criteria_error.html
{% extends "show_detail.html" %}
{% block errormessage %}
       Please input a valid criteria for search!
{% endblock %}

templates/search/index.html
{% extends 'base.html' %}
{% block newtask %}
    <div>
        <h2>Start A New Estimation</h2>
    </div>
    <div class="col-md-10">
         <form action="." method="POST" class="form-horizontal" role="form" id="myForm">
         {% csrf_token %}
            <div class="row">
              <label class="col-sm-2 control-label for=id_category"> Category: </label>
              <div class="col-md-4">
                <select class="input-sm" name="category" id="id_category">
                  <option>LED</option>
                  <option>Mother</option>
                  <option>Daughter</option>
                  <option>Carrier</option>
                  <option>Other</option>
                </select>
              </div>
            </div>
             <div class="row">
                <label for="id_part_number2" class="col-sm-2 control-label">Part Number: </label>
                <div class="col-md-4">
                    <input type="text" class="form-control input-sm" id="id_part_number2" name="part_number2" placeholder="e.g. XXX-XXXXXX">
                </div>
                <div class="col-md-6">
                    <b class="text-warning">{{errormessage}}</b>
                </div>
             </div>
             <div class="row">
                <label for="id_dat_file_location" class="col-sm-2 control-label">Dat File Directory: </label>
                <div class="col-md-8">
                    <input type="text" class="form-control input-sm" id="id_dat_file_location" name="dat_file_location" placeholder="Directory">
                    <!--input type="file" id="id_dat_file_location" name="dat_file_location" value="Browse Directory" webkitdirectory="" directory=""-->
                </div>
             </div>

             <div class="text-center">
               <button type='submit' name="Start_Estimation" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Start Estimation</button>
             </div>

            <!-- Modal -->
            <div class='modal fade' id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Warning</h4>
                  </div>
                  <div class="modal-body">
                    This Part Number Already Exists in Our Database, Do You Want to Save Changes?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" name="Save_Anyway" class="btn btn-primary">Save Changes</button>
                  </div>
                </div>
              </div>
             </div>

         </form>
    </div>

{% endblock %}

templates/search/search.html
{%extends 'base.html'%}
{%block search%}
    <div class="form-group">
    <input type="text" name='part_number' id='id_part_number' placeholder="Enter Part Number" class="form-control">
    </div>
    <input type="submit" value="Search" class="btn btn-primary">
{% endblock %}

templates/search/test.html
<!DOCTYPE html>
<html>
<head lang="zh-cn">
    <meta charset="UTF-8">

    <link href="../../static/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="../../static/css/code.css">
    <link rel="stylesheet" href="../../static/css/reset.css">
    <link rel="stylesheet" href="../../static/css/style.css">
    <link rel="stylesheet" href="../../static/css/mine.css">
    <script src="../../static/jquery.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>


    <title></title>
</head>
<body>
     <form action="." method="POST" class="form-horizontal" role="form">
     {% csrf_token %}
         <!--div class="form-group">
            <label for="id_part_number2" class="col-sm-2 control-label">Part Number: </label>
            <div class="col-md-3">
                <input type="text" class="form-control input-sm" id="id_part_number2" name="part_number2" placeholder="e.g. XXX-XXXXXX">
            </div>
         </div>
         <div class="form-group">
            <label for="id_dat_file_location" class="col-sm-2 control-label">Dat File Directory: </label>
            <div class="col-md-6">
                <input type="text" class="form-control input-sm" id="id_dat_file_location" name="dat_file_location" placeholder="Directory"><!--input type="file" id="exampleInputFile">
            </div>
         </div>
         <div class="form-action">
             <div class="text-center">
               <button type='submit' class="btn-lg btn-primary">Start Estimation</button>
             </div>
         </div-->
         {{ form }}
         <input type="submit" value="Submit" />
     </form>


    <!-- Button trigger modal -->
    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Collapsible Group Item #1
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Collapsible Group Item #2
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Collapsible Group Item #3
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>
</body>
</html>